In [2]:
import numpy as np

In [3]:
x = np.array([1, 2, 3])

In [5]:
x.__class__

numpy.ndarray

In [6]:
x.shape

(3,)

In [7]:
x.ndim

1

In [8]:
w = np.array([[1, 2, 3], [4, 5, 6]])

In [9]:
w.shape

(2, 3)

In [10]:
w.ndim

2

In [11]:
W = np.array([[1,2,3], [4,5,6]])

In [12]:
X = np.array([[0,1,2], [3,4,5]])

In [13]:
W  + X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [14]:
W * X

array([[ 0,  2,  6],
       [12, 20, 30]])

In [15]:
A = np.array([[1,2], [3,4]])

In [16]:
A * 10

array([[10, 20],
       [30, 40]])

In [17]:
A = np.array([[1,2], [3,4]])

In [18]:
b = np.array([10,20])

In [19]:
A * b

array([[10, 40],
       [30, 80]])

In [20]:
a = np.array([1,2,3])

In [21]:
b = np.array([4,5,6])

In [22]:
np.dot(a,b)

32

In [23]:
np.dot(b,a)

32

In [24]:
A = np.array([[1,2], [3,4]])

In [25]:
B = np.array([[5,6], [7,8]])

In [26]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])