In [2]:
import numpy as np

In [3]:
x = np.array([1, 2, 3])

In [5]:
x.__class__

numpy.ndarray

In [6]:
x.shape

(3,)

In [7]:
x.ndim

1

In [8]:
w = np.array([[1, 2, 3], [4, 5, 6]])

In [9]:
w.shape

(2, 3)

In [10]:
w.ndim

2

In [11]:
W = np.array([[1,2,3], [4,5,6]])

In [12]:
X = np.array([[0,1,2], [3,4,5]])

In [13]:
W  + X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [14]:
W * X

array([[ 0,  2,  6],
       [12, 20, 30]])

In [15]:
A = np.array([[1,2], [3,4]])

In [16]:
A * 10

array([[10, 20],
       [30, 40]])

In [17]:
A = np.array([[1,2], [3,4]])

In [18]:
b = np.array([10,20])

In [19]:
A * b

array([[10, 40],
       [30, 80]])

In [20]:
a = np.array([1,2,3])

In [21]:
b = np.array([4,5,6])

In [22]:
np.dot(a,b)

32

In [23]:
np.dot(b,a)

32

In [24]:
A = np.array([[1,2], [3,4]])

In [25]:
B = np.array([[5,6], [7,8]])

In [26]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [27]:
W1 = np.random.randn(2,4)

In [28]:
b1 = np.random.rand(4)

In [29]:
x = np.random.rand(10,2)

In [30]:
h = np.dot(x, W1) + b1

In [31]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [32]:
a = sigmoid(h)

In [33]:
print(a)

[[0.62408843 0.71764605 0.5580603  0.53482881]
 [0.52218572 0.72545225 0.50539422 0.69667413]
 [0.55082907 0.66589521 0.5389212  0.54956078]
 [0.6524234  0.76207954 0.55660324 0.58218591]
 [0.60885627 0.738142   0.54322111 0.59990062]
 [0.74238519 0.79280494 0.59469563 0.49421449]
 [0.56812284 0.68516999 0.54116556 0.55889347]
 [0.61432031 0.71249238 0.55490042 0.54006956]
 [0.62758775 0.75704608 0.54570498 0.61039459]
 [0.50804407 0.69248912 0.50980501 0.65840092]]
