In [1]:
import numpy as np

In [5]:
W1 = np.random.randn(2, 4)
b1 = np.random.randn(4)
x = np.random.randn(10, 2)
h = np.dot(x, W1) + b1
h

array([[-0.42224687,  1.56704122,  0.66022595,  0.92697875],
       [ 0.17979723,  0.09683821,  1.4923507 ,  2.03322544],
       [-1.5773719 ,  4.01736914, -0.86925297, -0.38698367],
       [-0.29831403,  0.68250044,  0.93689675,  2.42457147],
       [-0.72130921,  1.5351765 ,  0.38489524,  2.04076273],
       [-1.11489735,  2.61334703, -0.18030009,  1.06217599],
       [-1.90576238,  3.96890529, -1.16914448,  0.8654306 ],
       [-0.04808098,  0.24574463,  1.25119312,  2.50395672],
       [ 0.28775394,  0.26290618,  1.56375048,  1.29385949],
       [-1.44648513,  3.95191766, -0.73437449, -0.70117045]])

In [6]:
# シグモイド関数
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [8]:
a = sigmoid(h)
a

array([[0.39597922, 0.8273614 , 0.65931114, 0.71646194],
       [0.54482861, 0.52419065, 0.81643084, 0.88424164],
       [0.17116801, 0.98231802, 0.29540977, 0.40444363],
       [0.42596968, 0.66429654, 0.71847239, 0.91868191],
       [0.32710475, 0.82276244, 0.59505323, 0.88501091],
       [0.246959  , 0.93171565, 0.45504669, 0.74310616],
       [0.12945768, 0.98145626, 0.23700966, 0.70379401],
       [0.48798207, 0.56112883, 0.77750633, 0.92441874],
       [0.57144617, 0.56535056, 0.82689086, 0.78479973],
       [0.1905431 , 0.98114455, 0.32423551, 0.33155277]])

In [9]:
W2 = np.random.randn(4, 3)
b2 = np.random.randn(3)

s = np.dot(a, W2) + b2
s

array([[ 1.46433935,  0.55250197,  2.14292176],
       [ 1.4790805 ,  0.73265727,  2.30799036],
       [ 1.08697998,  0.15518054,  1.80538651],
       [ 1.44399156,  0.57354686,  2.10386177],
       [ 1.38963603,  0.37988667,  1.89226014],
       [ 1.27698162,  0.21860859,  1.76017448],
       [ 1.03667621, -0.11383077,  1.41217177],
       [ 1.45309174,  0.66794416,  2.21490991],
       [ 1.51513862,  0.7782531 ,  2.39378846],
       [ 1.11664576,  0.24270748,  1.92529607]])

レイヤの実装

In [10]:
# Sigmoid レイヤ
class Sigmoid:
    def __init__(self):
        self.params = []
    
    def forward(self, x):
        return 1 / (1 + np.exp(-x))

In [11]:
class Affine:
    def __init__(self, W ,b):
        self.params = [W, b]
    
    def forward(self, x):
        W, b = self.params
        out = np.dot(x, W) + b
        return out

In [12]:
class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size

        # 重みとバイアスの初期化
        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)

        # レイヤの作成
        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]

        # 全ての重みをリストにまとめる
        self.params = []
        for layer in self.layers:
            self.params += layer.params
    
    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x

In [14]:
x = np.random.randn(10, 2)
model = TwoLayerNet(2, 4, 3)
s = model.predict(x)
print(x)
print(s)

[[-0.75216228  0.07514337]
 [ 0.49638474 -1.75063982]
 [ 0.23425913 -0.6243663 ]
 [-0.49058151 -1.23916602]
 [ 0.47941755  1.77618136]
 [ 0.46555703 -0.33058665]
 [ 1.29270791 -1.94686817]
 [-1.0333672   1.42606001]
 [-0.6400792  -0.06105716]
 [-0.6127139   1.66002576]]
[[-1.91521995  1.39829279  0.39285267]
 [-1.48628577  1.07983589  0.46590805]
 [-1.4005733   1.16915906  0.4097734 ]
 [-1.98471675  1.33635938  0.43897027]
 [-0.69769257  1.12151623  0.30725504]
 [-1.12322085  1.11612876  0.38562033]
 [-0.89076776  0.89586155  0.44825404]
 [-1.84705016  1.45040984  0.35210819]
 [-1.88420537  1.37589     0.39845488]
 [-1.51132759  1.38840601  0.32738786]]
