In [1]:
import numpy as np

In [2]:
x = np.array([1, 2, 3])

In [3]:
x.__class__

numpy.ndarray

In [4]:
x.shape

(3,)

In [5]:
x.ndim

1

In [6]:
w = np.array([[1, 2, 3], [4, 5, 6]])

In [7]:
w.shape

(2, 3)

In [8]:
w.ndim

2

In [9]:
W = np.array([[1,2,3], [4,5,6]])

In [10]:
X = np.array([[0,1,2], [3,4,5]])

In [11]:
W  + X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [12]:
W * X

array([[ 0,  2,  6],
       [12, 20, 30]])

In [13]:
A = np.array([[1,2], [3,4]])

In [14]:
A * 10

array([[10, 20],
       [30, 40]])

In [15]:
A = np.array([[1,2], [3,4]])

In [16]:
b = np.array([10,20])

In [17]:
A * b

array([[10, 40],
       [30, 80]])

In [18]:
a = np.array([1,2,3])

In [19]:
b = np.array([4,5,6])

In [20]:
np.dot(a,b)

32

In [21]:
np.dot(b,a)

32

In [22]:
A = np.array([[1,2], [3,4]])

In [23]:
B = np.array([[5,6], [7,8]])

In [24]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [25]:
W1 = np.random.randn(2,4)

In [26]:
b1 = np.random.rand(4)

In [27]:
x = np.random.rand(10,2)

In [28]:
h = np.dot(x, W1) + b1

In [29]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [30]:
a = sigmoid(h)

In [31]:
print(a)

[[0.72193419 0.92415696 0.261182   0.86363928]
 [0.73351835 0.80256008 0.47111233 0.74269175]
 [0.64889344 0.68433121 0.54860043 0.77027485]
 [0.69426045 0.89568484 0.30526002 0.85902971]
 [0.68593411 0.95779715 0.16327188 0.92309623]
 [0.77016587 0.88353566 0.37177455 0.76625382]
 [0.75964461 0.98354797 0.09653249 0.93044417]
 [0.66897336 0.83864159 0.38407691 0.83847924]
 [0.66124054 0.64207198 0.59314448 0.73349109]
 [0.77359691 0.96776727 0.16304999 0.8852541 ]]


In [32]:
class Sigmoid:
    def __init__(self):
        self.parms = []

    def forward(self, x):
        return 1/(1+np.exp(-x))

In [33]:
class Affine:
    def __init__(self, W, b):
        self.parms = [W, b]

    def forward(self, x):
        W, b = self.parms
        out = np.dot(x, W) + b
        return out

In [34]:
class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size

        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)

        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]

        self.parms = []
        for layer in self.layers:
            self.parms += layer.parms

    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x

In [35]:
import numpy as np

In [36]:
x = np.random.randn(10,2)
model = TwoLayerNet(2,4,3)
s = model.predict(x)

In [37]:
print(s)

[[ 1.14024127  1.79720391  0.91911182]
 [ 0.47309513  1.77871953  1.52421389]
 [-0.01764149  1.86138994  2.22052395]
 [ 0.43492209  1.50951745  0.7459621 ]
 [-0.38878872  1.83564282  2.53203781]
 [ 0.34249313  1.90256317  2.00626695]
 [-0.04816055  1.71234701  1.85014911]
 [-0.75387927  1.8711356   2.98879232]
 [ 0.03233264  2.0517718   2.48891861]
 [ 1.05247309  1.60222902  0.35885928]]


In [38]:
D, N = 8, 7

In [39]:
x = np.random.randn(1, D)

In [40]:
#要素の複製(xをN回)
y = np.repeat(x, N, axis=0)

In [41]:
dy = np.random.randn(N, D)

In [42]:
dx = np.sum(dy, axis=0, keepdims=True)

In [43]:
x = np.random.randn(N, D)

In [44]:
y = np.sum(x, axis=0, keepdims=True)

In [45]:
dy = np.random.randn(1, D)

In [46]:
dx = np.repeat(dy, N, axis=0)

In [47]:
class MatMul:
    def __init__(self, W):
        self.parms = [W]
        self.grads = [np.zeros_like(W)]
        self.x = None

    def forward(self, x):
        W, = self.parms
        out = np.dot(x, W)
        self.x = x
        return out
    def backward(self, dout):
        W, = self.parms
        dx = np.dot(dout, W.T)
        dW = np.dot(self.x.T, dout)
        self.grads[0][...] = dW
        return dx

In [48]:
class Sigmoid:
    def __init__(self):
        self.parms, self.grads = [], []
        self.out = None

    def forward(self, x):
        out = 1 / (1+np.exp(-x))
        self.out = out
        return out
    
    def backward(self, dout):
        dx = dout * (1.0 - self.out) * self.out
        return dx



In [50]:
class Affine:
    def __init__(self, W, b):
        self.parms = [W, b]
        self.grads = [np.zeros_like(W), np.zeros_like(b)]
        self.x = None

    def forward(self, x):
        W, b = self.parms
        out = np.dot(x, W) + b
        self.x = x
        return out
    
    def backward(self, dout):
        W, b = self.parms
        dx = np.dot(dout, W.T)
        dW = np.dot(self.x.T, dout)
        db = np.sum(dout, axis=0)

        self.grads[0][...] = dW
        self.grads[1][...] = db
        return dx

In [58]:
import sys
sys.path.append('../deep-learning-from-scratch-2')
from dataset import spiral

ImportError: cannot import name 'spiral' from 'dataset' (C:\Users\mika2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\dataset\__init__.py)