In [2]:
import numpy as np

In [3]:
x = np.array([1, 2, 3])

In [5]:
x.__class__

numpy.ndarray

In [6]:
x.shape

(3,)

In [7]:
x.ndim

1

In [8]:
w = np.array([[1, 2, 3], [4, 5, 6]])

In [9]:
w.shape

(2, 3)

In [10]:
w.ndim

2

In [11]:
W = np.array([[1,2,3], [4,5,6]])

In [12]:
X = np.array([[0,1,2], [3,4,5]])

In [13]:
W  + X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [14]:
W * X

array([[ 0,  2,  6],
       [12, 20, 30]])

In [15]:
A = np.array([[1,2], [3,4]])

In [16]:
A * 10

array([[10, 20],
       [30, 40]])

In [17]:
A = np.array([[1,2], [3,4]])

In [18]:
b = np.array([10,20])

In [19]:
A * b

array([[10, 40],
       [30, 80]])

In [20]:
a = np.array([1,2,3])

In [21]:
b = np.array([4,5,6])

In [22]:
np.dot(a,b)

32

In [23]:
np.dot(b,a)

32

In [24]:
A = np.array([[1,2], [3,4]])

In [25]:
B = np.array([[5,6], [7,8]])

In [26]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [27]:
W1 = np.random.randn(2,4)

In [28]:
b1 = np.random.rand(4)

In [29]:
x = np.random.rand(10,2)

In [30]:
h = np.dot(x, W1) + b1

In [31]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [32]:
a = sigmoid(h)

In [33]:
print(a)

[[0.62408843 0.71764605 0.5580603  0.53482881]
 [0.52218572 0.72545225 0.50539422 0.69667413]
 [0.55082907 0.66589521 0.5389212  0.54956078]
 [0.6524234  0.76207954 0.55660324 0.58218591]
 [0.60885627 0.738142   0.54322111 0.59990062]
 [0.74238519 0.79280494 0.59469563 0.49421449]
 [0.56812284 0.68516999 0.54116556 0.55889347]
 [0.61432031 0.71249238 0.55490042 0.54006956]
 [0.62758775 0.75704608 0.54570498 0.61039459]
 [0.50804407 0.69248912 0.50980501 0.65840092]]


In [4]:
class Sigmoid:
    def __init__(self):
        self.parms = []

    def forward(self, x):
        return 1/(1+np.exp(-x))

In [3]:
class Affine:
    def __init__(self, W, b):
        self.parms = [W, b]

    def forward(self, x):
        W, b = self.parms
        out = np.dot(x, W) + b
        return out

In [10]:
class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size):
        I, H, O = input_size, hidden_size, output_size

        W1 = np.random.randn(I, H)
        b1 = np.random.randn(H)
        W2 = np.random.randn(H, O)
        b2 = np.random.randn(O)

        self.layers = [
            Affine(W1, b1),
            Sigmoid(),
            Affine(W2, b2)
        ]

        self.parms = []
        for layer in self.layers:
            self.parms += layer.parms

    def predict(self, x):
        for layer in self.layers:
            x = layer.forward(x)
        return x

In [7]:
import numpy as np

In [11]:
x = np.random.randn(10,2)
model = TwoLayerNet(2,4,3)
s = model.predict(x)

In [12]:
print(s)

[[0.27495024 3.018364   2.79990252]
 [0.27788573 2.97021877 3.01977265]
 [0.22716775 3.27259307 3.02556205]
 [0.34184926 2.64254925 2.85435741]
 [0.25196876 3.08817939 3.36981157]
 [0.24751139 3.15597299 2.96602923]
 [0.37630753 2.45934469 2.88809285]
 [0.31926619 2.62434642 3.35431655]
 [0.26379264 2.97893888 3.34749853]
 [0.34869015 2.59393249 2.89561493]]


In [13]:
D, N = 8, 7

In [14]:
x = np.random.randn(1, D)

In [15]:
#要素の複製(xをN回)
y = np.repeat(x, N, axis=0)

In [16]:
dy = np.random.randn(N, D)

In [17]:
dx = np.sum(dy, axis=0, keepdims=True)

In [18]:
x = np.random.randn(N, D)

In [19]:
y = np.sum(x, axis=0, keepdims=True)

In [20]:
dy = np.random.randn(1, D)

In [21]:
dx = np.repeat(dy, N, axis=0)

In [23]:
class MatMul:
    def __init__(self, W):
        self.parms = [W]
        self.grads = [np.zeros_like(W)]
        self.x = None

    def forward(self, x):
        W, = self.parms
        out = np.dot(x, W)
        self.x = x
        return out
    def backward(self, dout):
        W, = self.parms
        dx = np.dot(dout, W.T)
        dW = np.dot(self.x.T, dout)
        self.grads[0][...] = dW
        return dx

In [ ]:
class Sigmoid_2:
    def __init__(self):
        self.parms, self.grads = [], []
        self.out = None

