In [1]:
import numpy as np

x = np.array([1, 2, 3])
x.__class__
x.shape
x.ndim

1

In [2]:
W = np.array([[1, 2, 3], [4, 5, 6]])
W.shape

(2, 3)

In [3]:
X = np.array([[0, 1, 2], [3, 4, 5]])

In [4]:
W*X

array([[ 0,  2,  6],
       [12, 20, 30]])

In [5]:
A = np.array([[1, 2], [3, 4]])
A * 10

array([[10, 20],
       [30, 40]])

In [6]:
# ベクトルの内積
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.dot(a, b)

32

In [7]:
# 行列の積
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [8]:
import numpy as np
W1 = np.random.randn(2, 4)
b1 = np.random.randn(4)
W2 = np.random.randn(4, 3)
b2 = np.random.randn(3)
x = np.random.randn(10, 2)

h = np.dot(x, W1) + b1
a = sigmoid(h)
s = np.dot(a, W2) + b2 

In [9]:
def sigmoid(x):
    return 1 / (1+np.exp(-x))

In [10]:
a = sigmoid(h)

In [13]:
import forward_net
x = np.random.randn(10, 2)
model = forward_net.TwoLayerNet(2, 4, 3)
s = model.predict(x)
s

array([[0.36495625, 1.96282595, 0.55587501],
       [0.8418435 , 1.92726879, 0.11369968],
       [0.91750707, 1.91468484, 0.04754519],
       [0.82121343, 1.91686631, 0.14412002],
       [0.63061726, 1.88846331, 0.29026464],
       [0.77021552, 1.86256026, 0.07737042],
       [0.48664057, 1.96659207, 0.42094385],
       [0.52552561, 1.9556753 , 0.43929555],
       [0.24892052, 1.99569021, 0.74809523],
       [0.51513732, 2.01911571, 0.45224081]])

終了
