In [5]:
import numpy as np

x = np.array([1, 2, 3])
x.__class__
x.shape
x.ndim

1

In [8]:
W = np.array([[1, 2, 3], [4, 5,6 ]])
W.shape
W.ndim

2

In [11]:
W = np.array([[1,2,3], [4,5,6]])
X = np.array([[0,1,2], [3,4,5]])
W + X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [12]:
W * X

array([[ 0,  2,  6],
       [12, 20, 30]])

In [13]:
A = np.array([[1,2], [3,4]])
A * 10

array([[10, 20],
       [30, 40]])