In [5]:
import numpy as np

x = np.array([1, 2, 3])
x.__class__
x.shape
x.ndim

1

In [8]:
W = np.array([[1, 2, 3], [4, 5,6 ]])
W.shape
W.ndim

2

In [11]:
W = np.array([[1,2,3], [4,5,6]])
X = np.array([[0,1,2], [3,4,5]])
W + X

array([[ 1,  3,  5],
       [ 7,  9, 11]])

In [12]:
W * X

array([[ 0,  2,  6],
       [12, 20, 30]])

In [13]:
A = np.array([[1,2], [3,4]])
A * 10

array([[10, 20],
       [30, 40]])

In [14]:
A = np.array([[1,2], [3,4]])
b = np.array([10,20])
A * b

array([[10, 40],
       [30, 80]])

In [15]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.dot(a,b)

32

In [16]:
A = np.array([[1,2], [3,4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A,B)

array([[19, 22],
       [43, 50]])

In [17]:
W1 = np.random.randn(2, 4)
b1 = np.random.randn(4)
x = np.random.randn(10, 2)
h = np.dot(x, W1) + b1

In [18]:
def sigmoid(x):
  return 1/(1 + np.exp(-x))

In [19]:
a = sigmoid(h)

In [20]:
x = np.random.randn(10, 2)
W1 = np.random.randn(2, 4)
b1 = np.random.randn(4)
W2 = np.random.randn(4, 3)
b2 = np.random.randn(3)

h = np.dot(x, W1) + b1
a = sigmoid(h)
s = np.dot(a, W2) + b2